### ISSUE TITLE
Сбой на последнем шаге установки системы ZENLIX-2

### ISSUE THREAD

**Issue by ArslanaliDag** [ZENLIX/ZENLIX-2#1]
Добрый день.
Система: Ubuntu amd64.
Установку ZENLIX-2 произвожу под пользователей системы: root
База создана из CP VESTA.
Не могу понять в чем дело, все требуемые права при установке системы даны(777).
На третьем шаге пустота, нет никаких сообщений, ошибок и надписей.
![1](https://user-images.githubusercontent.com/11228826/57831482-e837b500-77bd-11e9-9115-69a265ab74ff.JPG)
![2](https://user-images.githubusercontent.com/11228826/57831492-f2f24a00-77bd-11e9-836c-5b3e7a1d5c11.JPG)

**Comment by ArslanaliDag** [comment]
Что еще проверить?

**Comment by techfaceus** [comment]
Попробуем собрать готовый образ VMDK и залить сюда.

**Comment by ArslanaliDag** [comment]
А что будет включать в себя этот VMDK, начинка?

**Comment by ArslanaliDag** [comment]
Мне хотелось бы разобраться почему не идет установка.
Как установить систему вручную?

**Comment by ArslanaliDag** [comment]
Нашел файлы бэкапа БД install.sql и update.sql.
Запустил, таблицы создались. Авторизовался.
Но не вижу стили и скрипты <link rel="stylesheet" href="/web/ZENLIX/js/bootstrap/css/bootstrap.min.css?2.95">
Как установить систему вручную?
![6](https://user-images.githubusercontent.com/11228826/57921943-370d4980-78a7-11e9-93d3-37f8b29c8c83.JPG)

**Comment by techfaceus** [comment]
> А что будет включать в себя этот VMDK, начинка?

готовый esx образ с уже установленной ОС древней версии напр 14.04 и поддержкой php 5.6

Почему не идёт установка - вопрос не правильно сформулирован :) 
Правильным будет вопрос: После инсталляции что-то не работает... 

Ответ:
Прежде всего проверьте минимальные системные требования для работы системы. А именно наличие модулей:
mod_rewrite, php-ldap, php-imap 
Так же проверьте добавлены ли в планировщик cron задания, которые Вы сможете найти в меню "Администрирование"-"Настройки системы" - "Информация" (либо перейти по {URL-системы}/config?inform). 
Если всё сделано верно, и что-то не работает, в файле conf.php найдите строку:
```conf
$CONF_HD = array (
'debug_mode'	=> false
);
```
и змените на строку:
```conf
$CONF_HD = array (
'debug_mode'	=> true
);
```
После чего, повторите действие, которое не работает или работает не так как необходимо. Например если не приходят письма, то создайте такое событие, после которого бы письмо должно прийти и так далее.
Проверьте лог веб-сервера, error.log на наличие ошибок, или же создайте персональную заявку в Системе Заявок и прикрепите лог. Вы так же можете отправить лог сюда.
В завершение, верните параметр в файле conf.php в режим:
```conf
$CONF_HD = array (
'debug_mode'	=> false
);
```

Я лично бы сказал:
- проверить лог apache
- проверить конфигурацию apache (.htaccess его наличие/работу и тд)
- смотреть консоль веб-браузера, куда идёт линк стилей и почему не отвечает URL.

**Comment by techfaceus** [comment]
+ 

> Установку ZENLIX-2 произвожу под пользователей системы: root

Зачем root?
Делайте под admin

**Comment by ArslanaliDag** [comment]
> > Установку ZENLIX-2 произвожу под пользователей системы: root
> 
> Зачем root?
> Делайте под admin

**Comment by techfaceus** [comment]
[https://github.com/ZENLIX/ZENLIX-2/blob/master/VM/README](url)

**Comment by ArslanaliDag** [comment]
1) "Если всё сделано верно, и что-то не работает, в файле conf.php найдите строку:"
Этот файл у меня вообще пуст. Как я понял в него дожны были записаться настройки 
БД на этапе установки системы.
Права на этот файл 777.
База готова и создана на CP.

2) "mod_rewrite, php-ldap, php-imap"
Установлены

3) "Так же проверьте добавлены ли в планировщик cron задания, которые Вы сможете найти в меню "Администрирование"-"Настройки системы" - "Информация" (либо перейти по {URL-системы}/config?inform)."
Я е могу проверить это так как система не установлена.
После установки системы конечно же добавлю необходимые задания в CRON.

4) "$CONF_HD = array ('debug_mode'	=> true );"
Принудительно вставил эту строку отредактировав файл conf.php
Результата нет.


5) "Проверьте лог веб-сервера, error.log"
Не нашел ничего критичного.

6) "проверить конфигурацию apache (.htaccess его наличие/работу и тд)"
.htaccess
Файл есть в корневом каталоге ZENLIX
его содержимое
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]

7) "смотреть консоль веб-браузера, куда идёт линк стилей и почему не отвечает URL."
Ручная установка.
Развернул базу в CP, скопировал уже сконфигурированный файл conf.php с другой установленной и работающей системы 
ZENLIX поправив его на свои данные БД, авторизовался.
Линки ссылок не верны см фото выше.

Хотел бы подвести итог.
Проверил то что вы просите.
Но все равно не могу установить систему.
Разворачиваю на своей VPS.
Развернуть получилось на своем локальном сервере WAMP.

**Comment by Neur0z** [comment]
Всем привет!
Нашел эту удивительную CMS здесь и был очень удивлен.
А ведь сам еще когда-то юзал HD.rustem и пытался внедрить его на предприятии, но так и не смог сделать нормальный импорт через LDAP.
Попытался и я установить, получил такую же проблему как у топикстартера, чистый экран без результата.
Скачал образ OVA, переконвертировал его и импортнул в мой Proxmox VE. К сожалению, с образом тоже пришлось помучаться. Внутри виртуалки полностью перенастроил VestaCP,  исправил ошибки с правами в системе и установил.
Реально ли развернуть эту CMS на нынешние версии PHP, Node.js, и т.д.? Я так понимаю, именно в этом и есть проблема.
Дело в том, что OVA-образ импортируется только как VM, а я хотел бы сделать все на базе контейнера...

**Comment by techfaceus** [comment]
Привет, на версии PHP 7.x установить не получится, поддерживаются только PHP 5.6.x.
Отсюда белый экран и тд.
Разработка данной версии заморожена.
Есть платная версия ZENLIX 3.x - но это уже абсолютно другой продукт написанный с нуля на Laravel 5.5


От 19 июня 2019 г. в 18:22:23, Neur0z (notifications@github.com) написал:

**Comment by Neur0z** [comment]
Понял, спасибо.
Буду пробовать понижать версии софта, или уговаривать руководителя на покупку последнего релиза :) Никак не сдается.

**Comment by techfaceus** [comment]
Для тех, кто с GitHub и больши богатым жизненным опытом использования hd.rustem - есть персональные скидки 😉 


От 19 июня 2019 г. в 21:58:19, Neur0z (notifications@github.com) написал:
